"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-50BAE5D8B77255A1", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 <= 3", "name": "activate_at_most_three_modes", "requirement_zh": "最多启用3个生产模式", "rhs": 3, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "4*x_0 + 1*x_1 + 2*x_2 + 3*x_3 + 4*x_4 + 1*x_5 + 2*x_6 <= 7", "name": "production_resource_capacity", "requirement_zh": "各模式生产资源占用为模式A=4、模式B=1、模式C=2、模式D=3、模式E=4、模式F=1、模式G=2；总占用不得超过7", "rhs": 7, "sense": "<=", "source": "public_problem", "terms": {"x_0": 4, "x_1": 1, "x_2": 2, "x_3": 3, "x_4": 4, "x_5": 1, "x_6": 2}}, {"expression": "1*x_0 + 1*x_1 <= 1", "name": "evidence_nonoverlap", "rhs": 1, "sense": "<=", "source": "CLAIM-F80524D71E03AD50", "terms": {"x_0": 1, "x_1": 1}}], "family": "production_capacity", "metadata": {"base_requirements_zh": ["最多启用3个生产模式", "各模式生产资源占用为模式A=4、模式B=1、模式C=2、模式D=3、模式E=4、模式F=1、模式G=2；总占用不得超过7"], "capacity": 7, "family_template": "production_capacity", "family_zh": "生产与容量规划", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 0}, "model_id": "SWOR087_patched", "objective": {"constant": 0, "name": "maximize_production_contribution", "terms": {"x_0": 1007, "x_1": 965, "x_2": 904, "x_3": 843, "x_4": 801, "x_5": 740, "x_6": 698}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR087", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "模式A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "模式B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "模式C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "模式D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "模式E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "模式F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "模式G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
