"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6", "x_7"], "base_id": "BASE-BC6BBF0D87FC0C95", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 + 1*x_7 <= 3", "name": "activate_at_most_three_modes", "requirement_zh": "最多启用3个生产模式", "rhs": 3, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1, "x_7": 1}}, {"expression": "4*x_0 + 1*x_1 + 2*x_2 + 3*x_3 + 4*x_4 + 1*x_5 + 2*x_6 + 3*x_7 <= 7", "name": "production_resource_capacity", "requirement_zh": "各模式生产资源占用为模式A=4、模式B=1、模式C=2、模式D=3、模式E=4、模式F=1、模式G=2、模式H=3；总占用不得超过7", "rhs": 7, "sense": "<=", "source": "public_problem", "terms": {"x_0": 4, "x_1": 1, "x_2": 2, "x_3": 3, "x_4": 4, "x_5": 1, "x_6": 2, "x_7": 3}}, {"expression": "1*x_1 + 1*x_4 + 1*x_7 == 1", "name": "variant_second_fallback", "requirement_zh": "第二核心候选模式B、其备用项模式E与末端应急项模式H中恰好启用一个", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_7": 1}}, {"expression": "1*x_0 + 1*x_1 <= 1", "name": "evidence_nonoverlap", "rhs": 1, "sense": "<=", "source": "CLAIM-D08E9D4CEE7FEAA6", "terms": {"x_0": 1, "x_1": 1}}], "family": "production_capacity", "metadata": {"base_requirements_zh": ["最多启用3个生产模式", "各模式生产资源占用为模式A=4、模式B=1、模式C=2、模式D=3、模式E=4、模式F=1、模式G=2、模式H=3；总占用不得超过7", "第二核心候选模式B、其备用项模式E与末端应急项模式H中恰好启用一个"], "capacity": 7, "family_template": "production_capacity", "family_zh": "生产与容量规划", "item_count": 8, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 4}, "model_id": "SWOR085_patched", "objective": {"constant": 0, "name": "maximize_production_contribution", "terms": {"x_0": 1018, "x_1": 957, "x_2": 896, "x_3": 854, "x_4": 793, "x_5": 751, "x_6": 690, "x_7": 629}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR085", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "模式A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "模式B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "模式C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "模式D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "模式E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "模式F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "模式G", "ub": 1, "vartype": "B"}, {"domain_expression": "x_7 in {0,1}", "lb": 0, "name": "x_7", "semantic_name": "模式H", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
