"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5"], "base_id": "BASE-07A1D1607415E48B", "constraints": [{"expression": "1*x_0 + 1*x_3 == 1", "name": "choose_one_leg_stage_1", "requirement_zh": "运输链第1段必须且只能从路径包A、路径包D中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1}}, {"expression": "1*x_1 + 1*x_4 == 1", "name": "choose_one_leg_stage_2", "requirement_zh": "运输链第2段必须且只能从路径包B、路径包E中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1}}, {"expression": "1*x_2 + 1*x_5 == 1", "name": "choose_one_leg_stage_3", "requirement_zh": "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_0 + -1*z_trigger == 0", "name": "evidence_trigger_link", "rhs": 0, "sense": "==", "source": "CLAIM-D77BA88D18B229B1", "terms": {"x_0": 1, "z_trigger": -1}}, {"expression": "1*x_1 + 1*z_trigger <= 1", "name": "evidence_trigger_exclusion", "rhs": 1, "sense": "<=", "source": "CLAIM-D77BA88D18B229B1", "terms": {"x_1": 1, "z_trigger": 1}}], "family": "routing_transport", "metadata": {"base_requirements_zh": ["运输链第1段必须且只能从路径包A、路径包D中采用一个候选路径包", "运输链第2段必须且只能从路径包B、路径包E中采用一个候选路径包", "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包"], "capacity": 6, "family_template": "routing_transport", "family_zh": "路径与运输", "item_count": 6, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 0}, "model_id": "SWOR059_patched", "objective": {"constant": 0, "name": "maximize_route_service_value", "terms": {"x_0": 1000, "x_1": 958, "x_2": 897, "x_3": 855, "x_4": 794, "x_5": 752}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR059", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "路径包A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "路径包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "路径包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "路径包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "路径包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "路径包F", "ub": 1, "vartype": "B"}, {"domain_expression": "z_trigger in {0,1}", "lb": 0, "name": "z_trigger", "semantic_name": "外部规则触发状态", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
