"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-CA58819E98E01D2E", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 == 3", "name": "hold_exactly_three_positions", "requirement_zh": "投资组合必须持有3个策略头寸", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "1*x_0 + 2*x_1 + 3*x_2 + 4*x_3 + 1*x_4 + 2*x_5 + 3*x_6 <= 12", "name": "portfolio_budget", "requirement_zh": "各策略投资预算占用为策略包A=1、策略包B=2、策略包C=3、策略包D=4、策略包E=1、策略包F=2、策略包G=3；总占用不得超过12", "rhs": 12, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 2, "x_2": 3, "x_3": 4, "x_4": 1, "x_5": 2, "x_6": 3}}, {"expression": "4*x_0 + 1*x_1 + 3*x_2 + 5*x_3 + 2*x_4 + 4*x_5 + 1*x_6 <= 15", "name": "portfolio_risk_limit", "requirement_zh": "各策略风险点为策略包A=4、策略包B=1、策略包C=3、策略包D=5、策略包E=2、策略包F=4、策略包G=1；组合风险点数不得超过15", "rhs": 15, "sense": "<=", "source": "public_problem", "terms": {"x_0": 4, "x_1": 1, "x_2": 3, "x_3": 5, "x_4": 2, "x_5": 4, "x_6": 1}}, {"expression": "1*x_0 + 1*x_3 >= 1", "name": "variant_first_fallback", "requirement_zh": "第一核心候选策略包A与其备用项策略包D中至少启用一个", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1}}], "family": "finance_portfolio", "metadata": {"base_requirements_zh": ["投资组合必须持有3个策略头寸", "各策略投资预算占用为策略包A=1、策略包B=2、策略包C=3、策略包D=4、策略包E=1、策略包F=2、策略包G=3；总占用不得超过12", "各策略风险点为策略包A=4、策略包B=1、策略包C=3、策略包D=5、策略包E=2、策略包F=4、策略包G=1；组合风险点数不得超过15", "第一核心候选策略包A与其备用项策略包D中至少启用一个"], "capacity": 6, "family_template": "finance_portfolio", "family_zh": "金融与组合选择", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 3}, "model_id": "SWOR048_patched", "objective": {"constant": 0, "name": "maximize_risk_adjusted_portfolio_value", "terms": {"x_0": 1014, "x_1": 953, "x_2": 911, "x_3": 850, "x_4": 789, "x_5": 747, "x_6": 686}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR048", "variables": [{"domain_expression": "x_0 = 0", "lb": 0, "name": "x_0", "semantic_name": "策略包A", "ub": 0, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "策略包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "策略包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "策略包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "策略包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "策略包F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "策略包G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
