"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-8DD58984ACA263BB", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 == 3", "name": "use_exactly_three_replenishment_blocks", "requirement_zh": "必须采用3个补货或供应块", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "1*x_0 + 1*x_1 + 1*x_3 + 1*x_6 >= 1", "name": "early_horizon_supply", "requirement_zh": "计划前段至少从补货包A、补货包B、补货包D、补货包G中安排一个可到货的供应块", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_2 + 1*x_4 >= 1", "name": "late_horizon_supply", "requirement_zh": "计划后段至少从补货包B、补货包C、补货包E中安排一个可到货的供应块", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_1": 1, "x_2": 1, "x_4": 1}}, {"expression": "1*x_5 + 1*x_6 >= 1", "name": "evidence_service_quota", "rhs": 1, "sense": ">=", "source": "CLAIM-B1F5EBB40DC13AD5", "terms": {"x_5": 1, "x_6": 1}}], "family": "inventory_supply_chain", "metadata": {"base_requirements_zh": ["必须采用3个补货或供应块", "计划前段至少从补货包A、补货包B、补货包D、补货包G中安排一个可到货的供应块", "计划后段至少从补货包B、补货包C、补货包E中安排一个可到货的供应块"], "capacity": 9, "family_template": "inventory_supply_chain", "family_zh": "库存与供应链", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 0}, "model_id": "SWOR089_patched", "objective": {"constant": 0, "name": "maximize_replenishment_value", "terms": {"x_0": 1004, "x_1": 962, "x_2": 901, "x_3": 859, "x_4": 798, "x_5": 737, "x_6": 695}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR089", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "补货包A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "补货包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "补货包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "补货包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "补货包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "补货包F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "补货包G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
