"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5"], "base_id": "BASE-EA26277D1C0B054E", "constraints": [{"expression": "1*x_0 + 1*x_3 == 1", "name": "choose_one_leg_stage_1", "requirement_zh": "运输链第1段必须且只能从路径包A、路径包D中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1}}, {"expression": "1*x_1 + 1*x_4 == 1", "name": "choose_one_leg_stage_2", "requirement_zh": "运输链第2段必须且只能从路径包B、路径包E中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1}}, {"expression": "1*x_2 + 1*x_5 == 1", "name": "choose_one_leg_stage_3", "requirement_zh": "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_1 + 1*x_4 + 1*x_5 == 1", "name": "variant_second_fallback", "requirement_zh": "第二核心候选路径包B、其备用项路径包E与末端应急项路径包F中恰好启用一个", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_5": 1}}, {"expression": "1*x_0 + 1*x_1 <= 1", "name": "evidence_nonoverlap", "rhs": 1, "sense": "<=", "source": "CLAIM-77AD1904E60BF686", "terms": {"x_0": 1, "x_1": 1}}], "family": "routing_transport", "metadata": {"base_requirements_zh": ["运输链第1段必须且只能从路径包A、路径包D中采用一个候选路径包", "运输链第2段必须且只能从路径包B、路径包E中采用一个候选路径包", "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "第二核心候选路径包B、其备用项路径包E与末端应急项路径包F中恰好启用一个"], "capacity": 7, "family_template": "routing_transport", "family_zh": "路径与运输", "item_count": 6, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 4}, "model_id": "SWOR058_patched", "objective": {"constant": 0, "name": "maximize_route_service_value", "terms": {"x_0": 1001, "x_1": 959, "x_2": 898, "x_3": 856, "x_4": 795, "x_5": 753}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR058", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "路径包A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "路径包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "路径包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "路径包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "路径包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "路径包F", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
