"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5"], "base_id": "BASE-47B7155E8EBFA41F", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 <= 3", "name": "activate_at_most_three_modes", "requirement_zh": "最多启用3个生产模式", "rhs": 3, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1}}, {"expression": "1*x_0 + 2*x_1 + 3*x_2 + 4*x_3 + 1*x_4 + 2*x_5 <= 6", "name": "production_resource_capacity", "requirement_zh": "各模式生产资源占用为模式A=1、模式B=2、模式C=3、模式D=4、模式E=1、模式F=2；总占用不得超过6", "rhs": 6, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 2, "x_2": 3, "x_3": 4, "x_4": 1, "x_5": 2}}, {"expression": "1*x_1 + 1*x_4 + 1*x_5 == 1", "name": "variant_second_fallback", "requirement_zh": "第二核心候选模式B、其备用项模式E与末端应急项模式F中恰好启用一个", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_5": 1}}], "family": "production_capacity", "metadata": {"base_requirements_zh": ["最多启用3个生产模式", "各模式生产资源占用为模式A=1、模式B=2、模式C=3、模式D=4、模式E=1、模式F=2；总占用不得超过6", "第二核心候选模式B、其备用项模式E与末端应急项模式F中恰好启用一个"], "capacity": 6, "family_template": "production_capacity", "family_zh": "生产与容量规划", "item_count": 6, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 4}, "model_id": "SWOR036_patched", "objective": {"constant": 0, "name": "maximize_production_contribution", "terms": {"x_0": 1009, "x_1": 948, "x_2": 906, "x_3": 845, "x_4": 803, "x_5": 742}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR036", "variables": [{"domain_expression": "x_0 = 0", "lb": 0, "name": "x_0", "semantic_name": "模式A", "ub": 0, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "模式B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "模式C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "模式D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "模式E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "模式F", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
