"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-FA5FDA413EDBE2B1", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 == 3", "name": "make_exactly_three_assignments", "requirement_zh": "必须完成3个分配", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "1*x_0 + 1*x_3 + 1*x_6 <= 1", "name": "worker_exclusivity_1", "requirement_zh": "资源主体1对应的匹配A、匹配D、匹配G中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_4 <= 1", "name": "worker_exclusivity_2", "requirement_zh": "资源主体2对应的匹配B、匹配E中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1}}, {"expression": "1*x_2 + 1*x_5 <= 1", "name": "worker_exclusivity_3", "requirement_zh": "资源主体3对应的匹配C、匹配F中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_1 + 1*x_4 + 1*x_6 == 1", "name": "variant_second_fallback", "requirement_zh": "第二核心候选匹配B、其备用项匹配E与末端应急项匹配G中恰好启用一个", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_6": 1}}, {"expression": "1*x_0 + 1*x_1 <= 1", "name": "evidence_nonoverlap", "rhs": 1, "sense": "<=", "source": "CLAIM-50E023BEE928DE92", "terms": {"x_0": 1, "x_1": 1}}], "family": "assignment_matching", "metadata": {"base_requirements_zh": ["必须完成3个分配", "资源主体1对应的匹配A、匹配D、匹配G中至多完成一个分配", "资源主体2对应的匹配B、匹配E中至多完成一个分配", "资源主体3对应的匹配C、匹配F中至多完成一个分配", "第二核心候选匹配B、其备用项匹配E与末端应急项匹配G中恰好启用一个"], "capacity": 8, "family_template": "assignment_matching", "family_zh": "分配与匹配", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 4}, "model_id": "SWOR044_patched", "objective": {"constant": 0, "name": "maximize_assignment_quality", "terms": {"x_0": 1008, "x_1": 947, "x_2": 905, "x_3": 844, "x_4": 802, "x_5": 741, "x_6": 699}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR044", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "匹配A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "匹配B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "匹配C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "匹配D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "匹配E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "匹配F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "匹配G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
