"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-AFC2AEA041C4B02E", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 == 3", "name": "make_exactly_three_assignments", "requirement_zh": "必须完成3个分配", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "1*x_0 + 1*x_3 + 1*x_6 <= 1", "name": "worker_exclusivity_1", "requirement_zh": "资源主体1对应的匹配A、匹配D、匹配G中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_4 <= 1", "name": "worker_exclusivity_2", "requirement_zh": "资源主体2对应的匹配B、匹配E中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1}}, {"expression": "1*x_2 + 1*x_5 <= 1", "name": "worker_exclusivity_3", "requirement_zh": "资源主体3对应的匹配C、匹配F中至多完成一个分配", "rhs": 1, "sense": "<=", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_0 + 1*x_1 + 1*x_2 >= 2", "name": "variant_core_service_floor", "requirement_zh": "前三个核心候选匹配A、匹配B、匹配C中至少启用两个", "rhs": 2, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1}}, {"expression": "1*x_5 + 1*x_6 >= 1", "name": "evidence_service_quota", "rhs": 1, "sense": ">=", "source": "CLAIM-2BA30DB2C50FA620", "terms": {"x_5": 1, "x_6": 1}}], "family": "assignment_matching", "metadata": {"base_requirements_zh": ["必须完成3个分配", "资源主体1对应的匹配A、匹配D、匹配G中至多完成一个分配", "资源主体2对应的匹配B、匹配E中至多完成一个分配", "资源主体3对应的匹配C、匹配F中至多完成一个分配", "前三个核心候选匹配A、匹配B、匹配C中至少启用两个"], "capacity": 7, "family_template": "assignment_matching", "family_zh": "分配与匹配", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 2}, "model_id": "SWOR086_patched", "objective": {"constant": 0, "name": "maximize_assignment_quality", "terms": {"x_0": 1002, "x_1": 960, "x_2": 899, "x_3": 857, "x_4": 796, "x_5": 735, "x_6": 693}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR086", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "匹配A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "匹配B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "匹配C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "匹配D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "匹配E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "匹配F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "匹配G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
