"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5"], "base_id": "BASE-A39ADD02B9F310E3", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 == 3", "name": "open_exactly_three_facilities", "requirement_zh": "必须建设3个设施或网络节点", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1}}, {"expression": "1*x_0 + 1*x_2 + 1*x_4 >= 1", "name": "cover_service_zone_1", "requirement_zh": "服务区1至少由节点A、节点C、节点E中的一个设施覆盖", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_2": 1, "x_4": 1}}, {"expression": "1*x_1 + 1*x_3 + 1*x_5 >= 1", "name": "cover_service_zone_2", "requirement_zh": "服务区2至少由节点B、节点D、节点F中的一个设施覆盖", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_1": 1, "x_3": 1, "x_5": 1}}], "family": "facility_network", "metadata": {"base_requirements_zh": ["必须建设3个设施或网络节点", "服务区1至少由节点A、节点C、节点E中的一个设施覆盖", "服务区2至少由节点B、节点D、节点F中的一个设施覆盖"], "capacity": 7, "family_template": "facility_network", "family_zh": "设施选址与网络设计", "item_count": 6, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 0}, "model_id": "SWOR100_patched", "objective": {"constant": 0, "name": "maximize_network_coverage_value", "terms": {"x_0": 1005, "x_1": 963, "x_2": 902, "x_3": 841, "x_4": 799, "x_5": 738}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR100", "variables": [{"domain_expression": "x_0 = 0", "lb": 0, "name": "x_0", "semantic_name": "节点A", "ub": 0, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "节点B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "节点C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "节点D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "节点E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "节点F", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
