"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_gurobi

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6"], "base_id": "BASE-BEE3B8720B3880B0", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 == 3", "name": "staff_exactly_three_shift_blocks", "requirement_zh": "本轮必须启用3个班次块", "rhs": 3, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1}}, {"expression": "1*x_0 + 1*x_3 + 1*x_6 >= 1", "name": "cover_period_1", "requirement_zh": "时段1至少由班次A、班次D、班次G中的一个班次块覆盖", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_4 >= 1", "name": "cover_period_2", "requirement_zh": "时段2至少由班次B、班次E中的一个班次块覆盖", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1}}, {"expression": "1*x_2 + 1*x_5 >= 1", "name": "cover_period_3", "requirement_zh": "时段3至少由班次C、班次F中的一个班次块覆盖", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_1 + 1*x_4 + 1*x_6 == 1", "name": "variant_second_fallback", "requirement_zh": "第二核心候选班次B、其备用项班次E与末端应急项班次G中恰好启用一个", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_6": 1}}, {"expression": "1*x_5 + 1*x_6 >= 1", "name": "evidence_service_quota", "rhs": 1, "sense": ">=", "source": "CLAIM-3865F6037479C688", "terms": {"x_5": 1, "x_6": 1}}], "family": "scheduling_workforce", "metadata": {"base_requirements_zh": ["本轮必须启用3个班次块", "时段1至少由班次A、班次D、班次G中的一个班次块覆盖", "时段2至少由班次B、班次E中的一个班次块覆盖", "时段3至少由班次C、班次F中的一个班次块覆盖", "第二核心候选班次B、其备用项班次E与末端应急项班次G中恰好启用一个"], "capacity": 9, "family_template": "scheduling_workforce", "family_zh": "排班与劳动力", "item_count": 7, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 4}, "model_id": "SWOR092_patched", "objective": {"constant": 0, "name": "maximize_covered_shift_value", "terms": {"x_0": 1000, "x_1": 958, "x_2": 897, "x_3": 855, "x_4": 794, "x_5": 752, "x_6": 691}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR092", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "班次A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "班次B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "班次C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "班次D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "班次E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "班次F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "班次G", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_gurobi(IR), ensure_ascii=False, sort_keys=True))
