"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6", "x_7"], "base_id": "BASE-7D988F4C2155460A", "constraints": [{"expression": "1*x_0 + 1*x_3 + 1*x_6 == 1", "name": "choose_one_leg_stage_1", "requirement_zh": "运输链第1段必须且只能从路径包A、路径包D、路径包G中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_4 + 1*x_7 == 1", "name": "choose_one_leg_stage_2", "requirement_zh": "运输链第2段必须且只能从路径包B、路径包E、路径包H中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_7": 1}}, {"expression": "1*x_2 + 1*x_5 == 1", "name": "choose_one_leg_stage_3", "requirement_zh": "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_0 + 1*x_3 >= 1", "name": "variant_first_fallback", "requirement_zh": "第一核心候选路径包A与其备用项路径包D中至少启用一个", "rhs": 1, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1}}], "family": "routing_transport", "metadata": {"base_requirements_zh": ["运输链第1段必须且只能从路径包A、路径包D、路径包G中采用一个候选路径包", "运输链第2段必须且只能从路径包B、路径包E、路径包H中采用一个候选路径包", "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "第一核心候选路径包A与其备用项路径包D中至少启用一个"], "capacity": 6, "family_template": "routing_transport", "family_zh": "路径与运输", "item_count": 8, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 3}, "model_id": "SWOR088_patched", "objective": {"constant": 0, "name": "maximize_route_service_value", "terms": {"x_0": 1003, "x_1": 961, "x_2": 900, "x_3": 858, "x_4": 797, "x_5": 736, "x_6": 694, "x_7": 633}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR088", "variables": [{"domain_expression": "x_0 = 0", "lb": 0, "name": "x_0", "semantic_name": "路径包A", "ub": 0, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "路径包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "路径包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "路径包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "路径包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "路径包F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "路径包G", "ub": 1, "vartype": "B"}, {"domain_expression": "x_7 in {0,1}", "lb": 0, "name": "x_7", "semantic_name": "路径包H", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
