"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6", "x_7"], "base_id": "BASE-37F9C4408901DAFA", "constraints": [{"expression": "1*x_0 + 1*x_3 + 1*x_6 == 1", "name": "choose_one_leg_stage_1", "requirement_zh": "运输链第1段必须且只能从路径包A、路径包D、路径包G中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_0": 1, "x_3": 1, "x_6": 1}}, {"expression": "1*x_1 + 1*x_4 + 1*x_7 == 1", "name": "choose_one_leg_stage_2", "requirement_zh": "运输链第2段必须且只能从路径包B、路径包E、路径包H中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_1": 1, "x_4": 1, "x_7": 1}}, {"expression": "1*x_2 + 1*x_5 == 1", "name": "choose_one_leg_stage_3", "requirement_zh": "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "rhs": 1, "sense": "==", "source": "public_problem", "terms": {"x_2": 1, "x_5": 1}}, {"expression": "1*x_0 + 1*x_1 + 1*x_2 >= 2", "name": "variant_core_service_floor", "requirement_zh": "前三个核心候选路径包A、路径包B、路径包C中至少启用两个", "rhs": 2, "sense": ">=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1}}, {"expression": "1*x_6 + 1*x_7 >= 1", "name": "evidence_service_quota", "rhs": 1, "sense": ">=", "source": "CLAIM-608828A1801D5847", "terms": {"x_6": 1, "x_7": 1}}], "family": "routing_transport", "metadata": {"base_requirements_zh": ["运输链第1段必须且只能从路径包A、路径包D、路径包G中采用一个候选路径包", "运输链第2段必须且只能从路径包B、路径包E、路径包H中采用一个候选路径包", "运输链第3段必须且只能从路径包C、路径包F中采用一个候选路径包", "前三个核心候选路径包A、路径包B、路径包C中至少启用两个"], "capacity": 8, "family_template": "routing_transport", "family_zh": "路径与运输", "item_count": 8, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 2}, "model_id": "SWOR029_patched", "objective": {"constant": 0, "name": "maximize_route_service_value", "terms": {"x_0": 1015, "x_1": 954, "x_2": 912, "x_3": 851, "x_4": 790, "x_5": 748, "x_6": 687, "x_7": 645}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR029", "variables": [{"domain_expression": "x_0 in {0,1}", "lb": 0, "name": "x_0", "semantic_name": "路径包A", "ub": 1, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "路径包B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "路径包C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "路径包D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "路径包E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "路径包F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "路径包G", "ub": 1, "vartype": "B"}, {"domain_expression": "x_7 in {0,1}", "lb": 0, "name": "x_7", "semantic_name": "路径包H", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
