"""Generated from canonical IR; do not edit by hand."""
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[2] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
from solver_backend import solve_copt

IR = json.loads('{"action_projection": ["x_0", "x_1", "x_2", "x_3", "x_4", "x_5", "x_6", "x_7"], "base_id": "BASE-8BF7E0BF56DCDB81", "constraints": [{"expression": "1*x_0 + 1*x_1 + 1*x_2 + 1*x_3 + 1*x_4 + 1*x_5 + 1*x_6 + 1*x_7 <= 3", "name": "activate_at_most_three_modes", "requirement_zh": "最多启用3个生产模式", "rhs": 3, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 1, "x_2": 1, "x_3": 1, "x_4": 1, "x_5": 1, "x_6": 1, "x_7": 1}}, {"expression": "1*x_0 + 2*x_1 + 3*x_2 + 4*x_3 + 1*x_4 + 2*x_5 + 3*x_6 + 4*x_7 <= 6", "name": "production_resource_capacity", "requirement_zh": "各模式生产资源占用为模式A=1、模式B=2、模式C=3、模式D=4、模式E=1、模式F=2、模式G=3、模式H=4；总占用不得超过6", "rhs": 6, "sense": "<=", "source": "public_problem", "terms": {"x_0": 1, "x_1": 2, "x_2": 3, "x_3": 4, "x_4": 1, "x_5": 2, "x_6": 3, "x_7": 4}}], "family": "production_capacity", "metadata": {"base_requirements_zh": ["最多启用3个生产模式", "各模式生产资源占用为模式A=1、模式B=2、模式C=3、模式D=4、模式E=1、模式F=2、模式G=3、模式H=4；总占用不得超过6"], "capacity": 6, "family_template": "production_capacity", "family_zh": "生产与容量规划", "item_count": 8, "selection_count": 3, "source_semantics": "public_problem", "structural_variant": 0}, "model_id": "SWOR061_patched", "objective": {"constant": 0, "name": "maximize_production_contribution", "terms": {"x_0": 1017, "x_1": 956, "x_2": 895, "x_3": 853, "x_4": 792, "x_5": 750, "x_6": 689, "x_7": 647}, "unit": "value_point"}, "schema_version": "1.0", "sense": "max", "single_objective": true, "task_id": "SWOR061", "variables": [{"domain_expression": "x_0 = 0", "lb": 0, "name": "x_0", "semantic_name": "模式A", "ub": 0, "vartype": "B"}, {"domain_expression": "x_1 in {0,1}", "lb": 0, "name": "x_1", "semantic_name": "模式B", "ub": 1, "vartype": "B"}, {"domain_expression": "x_2 in {0,1}", "lb": 0, "name": "x_2", "semantic_name": "模式C", "ub": 1, "vartype": "B"}, {"domain_expression": "x_3 in {0,1}", "lb": 0, "name": "x_3", "semantic_name": "模式D", "ub": 1, "vartype": "B"}, {"domain_expression": "x_4 in {0,1}", "lb": 0, "name": "x_4", "semantic_name": "模式E", "ub": 1, "vartype": "B"}, {"domain_expression": "x_5 in {0,1}", "lb": 0, "name": "x_5", "semantic_name": "模式F", "ub": 1, "vartype": "B"}, {"domain_expression": "x_6 in {0,1}", "lb": 0, "name": "x_6", "semantic_name": "模式G", "ub": 1, "vartype": "B"}, {"domain_expression": "x_7 in {0,1}", "lb": 0, "name": "x_7", "semantic_name": "模式H", "ub": 1, "vartype": "B"}], "world": "patched"}')
print(json.dumps(solve_copt(IR), ensure_ascii=False, sort_keys=True))
